### ISSUE TITLE
add `.sr-only` rule to `styles.less`

### ISSUE THREAD

**Issue by thephilgray** [thephilgray/gulp-epub-starter#76]
needs to be included for boilerplate project

```css
.sr-only {
  font-size: 0;
}
```
